services:
  postgresql: # postgres configuration
    container_name: postgresql_container
    image: bitnami/postgresql:15.4.0
    ports:
      - "5432:5432"
    networks:
      - batch_network
    volumes:
      - challenge_postgresql_data:/bitnami/postgresql
      - ./docker/init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=products
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD} # Password of user "postgres"
    
  app:
    build: #sping configuration to deploy
      context: ..
      dockerfile: Dockerfile  
    container_name: app_container
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      - batch_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/products
      SPRING_DATASOURCE_USERNAME: ${POSTGRESQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRESQL_PASSWORD}
      

volumes:
  challenge_postgresql_data:
    driver: local
  challenge_minio_data:
    driver: local

networks:
  batch_network:
    driver: bridge
